version: '3.8'

services:
  invoify:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: invoify-app
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - CHROME_BIN=/usr/bin/chromium
      - CHROME_PATH=/usr/bin/chromium
      - NODE_OPTIONS=--max-old-space-size=4096
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./public:/app/public:ro
    networks:
      - invoify-network

networks:
  invoify-network:
    driver: bridge 